name: "Setup Environment"
description: Setup PHP extensions, Composer, Node.js, and pnpm for CI in Docker container

inputs:
  # PHP Configuration
  php-version:
    description: PHP version to use
    required: false
    default: '8.5'
  php-extensions:
    description: PHP extensions to install (space-separated)
    required: false
    default: 'bcmath gd mbstring pcntl pdo_mysql zip'

  # Node/pnpm Configuration
  node-version:
    description: Node.js version to install
    required: false
    default: '24'
  pnpm-version:
    description: pnpm version to install
    required: false
    default: '10'

  # Feature Flags
  install-node:
    description: Whether to install Node.js and pnpm
    required: false
    default: 'true'
  build-assets:
    description: Whether to build frontend assets with Vite
    required: false
    default: 'true'
  run-migrations:
    description: Whether to run database migrations
    required: false
    default: 'false'

  # Composer Configuration
  composer-args:
    description: Additional arguments for composer install
    required: false
    default: '--quiet --prefer-dist --no-interaction --no-progress --optimize-autoloader'

runs:
  using: composite
  steps:
    # Step 1: Install system dependencies and PHP extensions
    # Using docker-php-ext-install for consistency with production environment
    - name: Install system dependencies and PHP extensions
      shell: bash
      run: |
        apt-get update -qq
        apt-get install -y --no-install-recommends \
          git \
          unzip \
          libonig-dev \
          libpng-dev \
          libxml2-dev \
          libzip-dev \
          default-mysql-client \
          curl

        # Install PHP extensions dynamically based on input
        docker-php-ext-install -j$(nproc) ${{ inputs.php-extensions }}

        # Install Redis extension
        pecl install redis && docker-php-ext-enable redis

        # Clean up apt cache to reduce image size
        rm -rf /var/lib/apt/lists/*

    # Step 2: Install Composer
    - name: Install Composer
      shell: bash
      run: |
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        composer --version

    # Step 3: Cache Composer dependencies
    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    # Step 4: Install Composer dependencies
    - name: Install Composer dependencies
      shell: bash
      run: composer install ${{ inputs.composer-args }}

    # Step 5: Setup Node.js and pnpm (conditional)
    - name: Setup pnpm
      if: inputs.install-node == 'true'
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      if: inputs.install-node == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    # Step 6: Install Node dependencies (conditional)
    - name: Install Node dependencies
      if: inputs.install-node == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    # Step 7: Setup Laravel environment
    - name: Copy environment file
      shell: bash
      run: cp .env.ci .env

    - name: Generate application key
      shell: bash
      run: php artisan key:generate

    # Step 8: Build frontend assets (conditional)
    - name: Build frontend assets
      if: inputs.build-assets == 'true'
      shell: bash
      run: pnpm vite build --logLevel error

    # Step 9: Run database migrations (conditional)
    - name: Run database migrations
      if: inputs.run-migrations == 'true'
      shell: bash
      run: php artisan migrate --force
