import type { Component, DirectiveOptions } from 'vue';

declare module '@/libraries/primevue/presets/lara' {
  const globalModule: Component;
  const directives: {
    tooltip: DirectiveOptions;
    badgedirective: DirectiveOptions;
    ripple: DirectiveOptions;
  };
  const autocomplete: Component;
  const calendar: Component;
  const cascadeselect: Component;
  const checkbox: Component;
  const chips: Component;
  const colorpicker: Component;
  const dropdown: Component;
  const inputgroup: Component;
  const inputgroupaddon: Component;
  const inputmask: Component;
  const inputnumber: Component;
  const inputswitch: Component;
  const inputtext: Component;
  const knob: Component;
  const listbox: Component;
  const multiselect: Component;
  const password: Component;
  const radiobutton: Component;
  const rating: Component;
  const selectbutton: Component;
  const slider: Component;
  const textarea: Component;
  const togglebutton: Component;
  const treeselect: Component;
  const tristatecheckbox: Component;
  const button: Component;
  const speeddial: Component;
  const splitbutton: Component;
  const datatable: Component;
  const dataview: Component;
  const orderlist: Component;
  const organizationchart: Component;
  const paginator: Component;
  const picklist: Component;
  const tree: Component;
  const treetable: Component;
  const timeline: Component;
  const accordion: Component;
  const card: Component;
  const deferredcontent: Component;
  const divider: Component;
  const fieldset: Component;
  const panel: Component;
  const scrollpanel: Component;
  const tabview: Component;
  const toolbar: Component;
  const confirmpopup: Component;
  const dialog: Component;
  const overlaypanel: Component;
  const sidebar: Component;
  const breadcrumb: Component;
  const contextmenu: Component;
  const dock: Component;
  const menu: Component;
  const menubar: Component;
  const megamenu: Component;
  const panelmenu: Component;
  const steps: Component;
  const tabmenu: Component;
  const tieredmenu: Component;
  const message: Component;
  const inlinemessage: Component;
  const toast: Component;
  const image: Component;
  const avatar: Component;
  const badge: Component;
  const blockui: Component;
  const chip: Component;
  const scrolltop: Component;
  const skeleton: Component;
  const progressbar: Component;
  const tag: Component;
  const terminal: Component;

  const defaultExport: {
    global: Component;
    directives: {
      tooltip: DirectiveOptions;
      badgedirective: DirectiveOptions;
      ripple: DirectiveOptions;
    };
    autocomplete: Component;
    calendar: Component;
    cascadeselect: Component;
    checkbox: Component;
    chips: Component;
    colorpicker: Component;
    dropdown: Component;
    inputgroup: Component;
    inputgroupaddon: Component;
    inputmask: Component;
    inputnumber: Component;
    inputswitch: Component;
    inputtext: Component;
    knob: Component;
    listbox: Component;
    multiselect: Component;
    password: Component;
    radiobutton: Component;
    rating: Component;
    selectbutton: Component;
    slider: Component;
    textarea: Component;
    togglebutton: Component;
    treeselect: Component;
    tristatecheckbox: Component;
    button: Component;
    speeddial: Component;
    splitbutton: Component;
    datatable: Component;
    dataview: Component;
    orderlist: Component;
    organizationchart: Component;
    paginator: Component;
    picklist: Component;
    tree: Component;
    treetable: Component;
    timeline: Component;
    accordion: Component;
    card: Component;
    deferredcontent: Component;
    divider: Component;
    fieldset: Component;
    panel: Component;
    scrollpanel: Component;
    tabview: Component;
    toolbar: Component;
    confirmpopup: Component;
    dialog: Component;
    overlaypanel: Component;
    sidebar: Component;
    breadcrumb: Component;
    contextmenu: Component;
    dock: Component;
    menu: Component;
    menubar: Component;
    megamenu: Component;
    panelmenu: Component;
    steps: Component;
    tabmenu: Component;
    tieredmenu: Component;
    message: Component;
    inlinemessage: Component;
    toast: Component;
    image: Component;
    avatar: Component;
    badge: Component;
    blockui: Component;
    chip: Component;
    scrolltop: Component;
    skeleton: Component;
    progressbar: Component;
    tag: Component;
    terminal: Component;
  };

  export default defaultExport;
}
