global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

tls:
  certificates:
    - certFile: /etc/traefik/certs/sassfolding.cert
      keyFile: /etc/traefik/certs/sassfolding.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/sassfolding.cert
        keyFile: /etc/traefik/certs/sassfolding.key

log:
  level: INFO
  format: common
