import type { Component, Directive } from 'vue';

declare module '@/libraries/primevue/presets/aura' {
  const globalModule: Component;
  const directives: {
    tooltip: Directive;
    ripple: Directive;
  };

  const autocomplete: Component;
  const cascadeselect: Component;
  const checkbox: Component;
  const colorpicker: Component;
  const datepicker: Component;
  const floatlabel: Component;
  const iconfield: Component;
  const inputgroup: Component;
  const inputotp: Component;
  const inputgroupaddon: Component;
  const inputmask: Component;
  const inputnumber: Component;
  const inputtext: Component;
  const knob: Component;
  const listbox: Component;
  const multiselect: Component;
  const password: Component;
  const radiobutton: Component;
  const rating: Component;
  const select: Component;
  const selectbutton: Component;
  const slider: Component;
  const textarea: Component;
  const togglebutton: Component;
  const toggleswitch: Component;
  const treeselect: Component;
  const button: Component;
  const speeddial: Component;
  const splitbutton: Component;
  const datatable: Component;
  const dataview: Component;
  const orderlist: Component;
  const organizationchart: Component;
  const paginator: Component;
  const picklist: Component;
  const tree: Component;
  const treetable: Component;
  const timeline: Component;
  const accordion: Component;
  const card: Component;
  const deferred: Component;
  const divider: Component;
  const fieldset: Component;
  const panel: Component;
  const scrollpanel: Component;
  const splitter: Component;
  const stepper: Component;
  const tabs: Component;
  const toolbar: Component;
  const confirmpopup: Component;
  const confirmdialog: Component;
  const dialog: Component;
  const drawer: Component;
  const popover: Component;
  const fileupload: Component;
  const breadcrumb: Component;
  const contextmenu: Component;
  const dock: Component;
  const menu: Component;
  const menubar: Component;
  const megamenu: Component;
  const panelmenu: Component;
  const tabmenu: Component;
  const tieredmenu: Component;
  const message: Component;
  const toast: Component;
  const carousel: Component;
  const galleria: Component;
  const image: Component;
  const avatar: Component;
  const badge: Component;
  const blockui: Component;
  const chip: Component;
  const inplace: Component;
  const metergroup: Component;
  const scrolltop: Component;
  const skeleton: Component;
  const progressbar: Component;
  const progressspinner: Component;
  const tag: Component;
  const terminal: Component;

  const defaultExport: {
    global: Component;
    directives: {
      tooltip: DirectiveOptions;
      ripple: DirectiveOptions;
    };
    autocomplete: Component;
    cascadeselect: Component;
    checkbox: Component;
    colorpicker: Component;
    datepicker: Component;
    floatlabel: Component;
    iconfield: Component;
    inputgroup: Component;
    inputotp: Component;
    inputgroupaddon: Component;
    inputmask: Component;
    inputnumber: Component;
    inputtext: Component;
    knob: Component;
    listbox: Component;
    multiselect: Component;
    password: Component;
    radiobutton: Component;
    rating: Component;
    select: Component;
    selectbutton: Component;
    slider: Component;
    textarea: Component;
    togglebutton: Component;
    toggleswitch: Component;
    treeselect: Component;
    button: Component;
    speeddial: Component;
    splitbutton: Component;
    datatable: Component;
    dataview: Component;
    orderlist: Component;
    organizationchart: Component;
    paginator: Component;
    picklist: Component;
    tree: Component;
    treetable: Component;
    timeline: Component;
    accordion: Component;
    card: Component;
    deferred: Component;
    divider: Component;
    fieldset: Component;
    panel: Component;
    scrollpanel: Component;
    splitter: Component;
    stepper: Component;
    tabs: Component;
    toolbar: Component;
    confirmpopup: Component;
    confirmdialog: Component;
    dialog: Component;
    drawer: Component;
    popover: Component;
    fileupload: Component;
    breadcrumb: Component;
    contextmenu: Component;
    dock: Component;
    menu: Component;
    menubar: Component;
    megamenu: Component;
    panelmenu: Component;
    tabmenu: Component;
    tieredmenu: Component;
    message: Component;
    toast: Component;
    carousel: Component;
    galleria: Component;
    image: Component;
    avatar: Component;
    badge: Component;
    blockui: Component;
    chip: Component;
    inplace: Component;
    metergroup: Component;
    scrolltop: Component;
    skeleton: Component;
    progressbar: Component;
    progressspinner: Component;
    tag: Component;
    terminal: Component;
  };

  export default defaultExport;
}
