name: Code Style Checks

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.1
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: hybridly
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run Laravel migrations
        run: php artisan migrate --force
      - name: Generate IDE Helper files
        run: |
          mkdir -p helpers
          php artisan ide-helper:eloquent
          php artisan ide-helper:generate
          php artisan ide-helper:meta
          php artisan ide-helper:models -M
        shell: bash
      - name: Run Laravel Pint
        run: php ./vendor/bin/pint --test
      - name: Run PHPStan
        run: php ./vendor/bin/phpstan analyze --memory-limit=2G
      - name: Run ESLint
        run: pnpm eslint . --max-warnings=0
      - name: Run vue-tsc
        run: pnpm vue-tsc --noEmit
