name: Code Style Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sassfolding_test
          MYSQL_USER: dummy_user
          MYSQL_PASSWORD: dummy_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Run Laravel migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: sassfolding_test
          DB_USERNAME: dummy_user
          DB_PASSWORD: dummy_password

      - name: Generate application key
        run: php artisan key:generate

      - name: Generate IDE Helper files
        run: |
          mkdir -p helpers
          php artisan ide-helper:generate
          php artisan ide-helper:models -F helpers/_ide_helper_models.php -M
          php artisan ide-helper:meta
        shell: bash

      - name: Run Laravel Pint
        run: php ./vendor/bin/pint --test

      - name: Run PHPStan
        run: php ./vendor/bin/phpstan analyze --memory-limit=2G

      - name: Run ESLint
        run: pnpm eslint . --max-warnings=0

      - name: Run vue-tsc
        run: pnpm vue-tsc --noEmit
